import DOMPurify from "dompurify";
import { JSDOM } from "jsdom";

const jsdom = new JSDOM("");

export function sanitizeSvg(svgContent: Buffer): Buffer {
	const svgString = svgContent.toString("utf-8");
	const purifier = DOMPurify(jsdom.window as Parameters<typeof DOMPurify>[0]);

	const cleaned = purifier.sanitize(svgString, {
		ALLOWED_TAGS: [
			"svg",
			"g",
			"path",
			"circle",
			"ellipse",
			"line",
			"polyline",
			"polygon",
			"rect",
			"text",
			"tspan",
			"defs",
			"style",
			"use",
			"image",
			"foreignObject",
			"symbol",
			"marker",
			"linearGradient",
			"radialGradient",
			"stop",
			"filter",
			"feBlend",
			"feColorMatrix",
			"feComponentTransfer",
			"feComposite",
			"feConvolveMatrix",
			"feDiffuseLighting",
			"feDisplacementMap",
			"feFlood",
			"feGaussianBlur",
			"feImage",
			"feMerge",
			"feMorphology",
			"feOffset",
			"feSpecularLighting",
			"feTile",
			"feTurbulence",
			"clip",
			"mask",
			"a",
			"title",
			"desc",
			"metadata",
		],
		ALLOWED_ATTR: [
			"xmlns",
			"xmlns:xlink",
			"viewBox",
			"width",
			"height",
			"x",
			"y",
			"cx",
			"cx",
			"cy",
			"r",
			"rx",
			"ry",
			"x1",
			"y1",
			"x2",
			"y2",
			"points",
			"d",
			"fill",
			"stroke",
			"stroke-width",
			"opacity",
			"transform",
			"style",
			"class",
			"id",
			"href",
			"xlink:href",
			"font-size",
			"font-family",
			"text-anchor",
			"dominant-baseline",
			"clip-path",
			"mask-id",
			"mask",
			"data-",
			"aria-",
			"role",
			"viewBox",
			"preserveAspectRatio",
			"version",
		],
		KEEP_CONTENT: true,
		FORCE_BODY: false,
		RETURN_TRUSTED_TYPE: false,
	});

	return Buffer.from(cleaned, "utf-8");
}
